### PR TITLE
this is my first draft of the view, serialize, and model for my payme…

### PR DESCRIPTION
**Pull request by BlaiseRoberts**
…nt type resource.  The customerID is commented out of my model for testing purpose but needs to be added once we create the model for Customer

## Associated Ticket
[Payment Type Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/13)

## Description 
You will need to test that the resource shows up in the root api and you can post data to it.  (The customerID still needs to be added after our customer resource is created)

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by ANMyers — APPROVED** [review]
Had some issues with testing your resources, but we came to a resolution by deleting the db file and migrating. The db needs to be updated to include the database file.

**Comment by BlaiseRoberts** [comment]
Steps to test:
checkout branch
python manage.py makemigrations api
python manage.py migrate
python manage.py runserver

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
The code worked on my machine after I deleted sqlite3.db, made migrations, then migrated. The first two field limits work as designed. The Account Label and Account Type accept alphanumeric characters and special characters. Both fields are limited to 20 characters. The Account Number field fails with ridiculously large numbers. I inserted "1231242349812745098347509823740598712094870239814701293847" and got an overflow error. We should probably insert a max character limit.

**Review by JeremyBakker — APPROVED** [review]
This now works as designed. The added limit is helpful. Thanks!

**Review by JeremyBakker — APPROVED** [review]
All functions as expected after merges.

**Review by willsims14 — APPROVED** [review]
Beautiful

**Pull request merged**
