### PR TITLE
AM created employee model, view and serializer

### PR DESCRIPTION
**Pull request by ANMyers**
## Associated Ticket
[Create Employee Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/15)

## Description 
Added model, view, serializer for employee table.
included import into __init__.py in views folder for simple importation into urls.py.
functional with department table.

*Remember to*:
delete the db.sqlite3 file
 ```python manage.py makemigrations api```
 ```python manage.py migrate```

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
This functions as expected. I like the IsSupervisor option and its default to False. Please check your docstrings. Some refer to "product type."

**Review by JeremyBakker — APPROVED** [review]

**Review by BlaiseRoberts — APPROVED** [review]
💯

**Review by willsims14 — CHANGES_REQUESTED** [review]
💯

**Review by willsims14 — APPROVED** [review]
⚰️

**Pull request merged**
