### PR TITLE
Add fixtures to seed these joining tables: OrderProduct, EmployeeTraining and EmployeeComputer

### PR DESCRIPTION
**Pull request by zakspence**
## Associated Ticket
[Create Training Program Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/14)
[Create Product Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/8)
[Create Computer Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/12)

## Description 
This pull request concerns the seeding of these tables in the database:
- EmployeeComputer
- EmployeeTraining
- OrderProduct

Commits create fixtures for each of the tables with seed data. 

To test that the data loads properly, run ```python manage.py builddb``` .

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by BlaiseRoberts — DISMISSED** [review]
Everything loaded in smoothly for me! 💯

**Review by ANMyers — CHANGES_REQUESTED** [review]
please remove 'The database has been loaded successfully.' response after importing.
besides that looks good.

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
Both the order and order_product models have an unnecessary line space after defining the class name and before the docstrings. Strike lines 34 and 35 in builddb.py.

**Comment by zakspence** [comment]
changes made @ANMyers

**Comment by zakspence** [comment]
changes made @JeremyBakker

**Review by JeremyBakker — APPROVED** [review]
All functions as expected. Data loads. Tables exist in database. Code looks clean and uniform. Thanks!

**Review by ANMyers — APPROVED** [review]
thank you for the change, looks good.

**Pull request merged**
