### PR TITLE
Zs customer resource

### PR DESCRIPTION
**Pull request by zakspence**
## Associated Ticket
[Create Customer resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/16)

## Description 
Customer resource has model, serializer and view implemented in django rest. Resource can be viewed and edited at /customers url.

Delete db.sqlite3 file before making migrations.

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by BlaiseRoberts — CHANGES_REQUESTED** [review]
Looks Good, you can remove the imports from you serializer and view to not import Users & Groups.  👍 Everything else seems to work for me!

**Review by ANMyers — APPROVED** [review]
she works! hazzah!

**Comment by zakspence** [comment]
Fixed the serializer and view files, @BlaiseRoberts

**Review by ANMyers — APPROVED** [review]
Looks good sir, functional as far as I can tell.

**Review by JeremyBakker — APPROVED** [review]
I can insert information in all the fields, and it persists in the database. All looks good. Thanks!

**Review by BlaiseRoberts — APPROVED** [review]

**Comment by BlaiseRoberts** [comment]
💯

**Pull request merged**
