### PR TITLE
Added serial_number field to the Computer model and created dummy data.

### PR DESCRIPTION
**Pull request by willsims14**
## Associated Ticket(s)
[Computer Needs serial_number Field](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/43)

[Create Dummy Data for Employee Half](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/40)

## Description 
Added field, "serial_number", to the Computer Resource model.

## Migrations
- [x] Yes

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by ANMyers — APPROVED** [review]
Nice, looks good and works, very nice to not have to enter a decommissioned date when buying a new laptop.

**Review by JeremyBakker — APPROVED** [review]
This looks and works as expected. I think 50 spaces is probably sufficient for the serial number. Thanks!

**Review by BlaiseRoberts — APPROVED** [review]
Looks great! Love the data, 🥇

**Review by zakspence — APPROVED** [review]
Merged zsam/... into this one and tested the model. runs great!

**Pull request merged**
