### PR TITLE
Add joining models for employee-training, employee-computer and order-product resources

### PR DESCRIPTION
**Pull request by zakspence**
## Associated Ticket
[Create Training Program Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/14)
[Create Product Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/8)
[Create Computer Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/12)

## Description 
Joining tables that model the relationships were joined for the following entities:
- The employee-computer table models a computer's assignment to employees throughoutits life at the company
- the employee-training table models the training programs employees have enrolled in
- the order-product table models the products listed as line items on a given order

## Migrations
- [ ] Yes
- [x] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
Check line 23 in model_employee-computer.py. I believe it should be ```computer_id = models.ForeignKey(Computer)```

**Review by JeremyBakker — DISMISSED** [review]

**Review by ANMyers — CHANGES_REQUESTED** [review]
After completing migrations and migrate the tables do not exist in the database, i believe we need serializers inorder to create the tables in the database.

**Comment by JeremyBakker** [comment]
We actually had a problem with the file names, and we failed to include the join tables in the \__init\__ file

**Review by ANMyers — APPROVED** [review]
Looks solid, good catch on the - for the file name

**Pull request merged**
