### PR TITLE
Added AdminCustomerSerializer so authenticated users see extra field.

### PR DESCRIPTION
**Pull request by willsims14**
## Associated Ticket
[Restrict Non-Super Users](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/35)

## Description 
Created new serializer and overwrote a method in view_customer.py

**TO TEST:**
* ```python manage.py builddb```
* ```python manage.py createsuperuser```
* ```python manage.py runserver```
* BEFORE logging in, make sure you CANNOT see the 'date_created' field under Customer table
* AFTER logging in, make sure you CAN see the 'date_created' field under Customer table

## Migrations
- [x] Yes

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
The code functions as I expect. I can see the appropriate data when logged in. The same data disappears when I log out. Please adjust the docstring on AdminCustomerSerializer to match the format of those already included. Also be sure to highlight the inclusion of all fields. Change the docstring on the CustomerSerializer to note that one field is excluded.

**Review by JeremyBakker — DISMISSED** [review]
Thanks for making the changes and for deleting the fixtures.

**Review by zakspence — APPROVED** [review]
My name is Zak Spence and I approve this merge

**Review by JeremyBakker — APPROVED** [review]
Great. Thanks!

**Pull request merged**
