### PR TITLE
Created Product Resource

### PR DESCRIPTION
**Pull request by willsims14**
## Associated Ticket
[Product Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/8)

## Description 
Product resource is now linked to ProductType and Customer table (via foreign key)

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
It all works as it should. The foreign key to the customer returns the customer object, but this should be fixed after jb-createOrderResource has merged. Let's check again after the merge.

**Review by ANMyers — APPROVED** [review]
Looks good sir, we'll have to update as we merge one at a time, but its functional as far as I can see.

**Comment by zakspence** [comment]
Looks good, just needs the change jeremy suggested

**Review by zakspence — APPROVED** [review]
Works as expected.

**Review by JeremyBakker — APPROVED** [review]
The customer foreign key works after the merge. Thanks!

**Review by BlaiseRoberts — APPROVED** [review]
💯

**Pull request merged**
