### PR TITLE
added model, serializer, view for training program

### PR DESCRIPTION
**Pull request by ANMyers**
## Associated Ticket
[Create Training Program Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/14)

## Description 
Added model, view, and serializer for training programs.
Added corresponding urls.py for viewing and testing.
corrected tabs into space indentation.

- corrected camelcase spelling in model
- added str method for returning the string of the name

Remember to:
delete the db.sqlite3 file
 ```python manage.py makemigrations api```
 ```python manage.py migrate```

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by zakspence — CHANGES_REQUESTED** [review]
The following files have mixed spaces and tabs:
- view_training_program
- view_product_type
- serializer_training_program
- model_training_program
- model_product_type

Please turn those tabs into spaces.

Elsewise it works fine.

**Review by zakspence — APPROVED** [review]

**Review by willsims14 — APPROVED** [review]
🔢

**Review by BlaiseRoberts — CHANGES_REQUESTED** [review]
please change maxenrollment to maxEnrollment.
also, please add a __str__ method to your model so we can easily identify as a foreign key in the future

**Review by JeremyBakker — APPROVED** [review]
This looks good to me. All functions as expected. We may want to speak with the product owner about field limits at some point. A training program end date can precede its start date, and the MaxEnrollment field allows cartoonish-sized numbers.

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
Check your docstrings. Some still refer to "product type."

**Review by JeremyBakker — APPROVED** [review]
Thank you for making those editorial changes.

**Review by BlaiseRoberts — APPROVED** [review]

**Review by JeremyBakker — APPROVED** [review]
Still good to go after merging the master that contains department.

**Comment by BlaiseRoberts** [comment]
💯

**Pull request merged**
