### PR TITLE
Created django project bangazon with app api.

### PR DESCRIPTION
**Pull request by ANMyers**
## Associated Ticket
[Project Setup](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/3)

## Description 
Created the project 'bangazon' with the app 'api' using django.
Created folders models, serializers, views which will contain corresponding py files.
Removed Urls.py from api directory.
Added 'rest_framework', 'bangazon.api' to INSTALLED_APPS.
Included base functionality for Users and Groups from tutorial to demonstrate setup.

## Migrations
- [x] No
- [ ] Yes

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by willsims14 — CHANGES_REQUESTED** [review]
Remove api/URLs.py because django rest doesn't put URLs inside of app directories

**Review by BlaiseRoberts — CHANGES_REQUESTED** [review]
You need to update your .gitignore file so your .DS_Store file is included in the file and deleted from your branch.
We need to add to the bangazon/settings.py file- specifically in the INSTALLED_APPS, details in the ticket.
Also, we need to add the router to our urls.py

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
Also add ```**/*.db``` and ```**/*.sqlite3``` to your .gitignore.

**Review by JeremyBakker — APPROVED** [review]
This looks okay to me. Thanks! I assume ```bangazon/bangazon/api/serializers/serializers.py``` is a template for us to use. Is that right?

**Review by willsims14 — APPROVED** [review]

**Review by BlaiseRoberts — APPROVED** [review]

**Review by BlaiseRoberts — CHANGES_REQUESTED** [review]
Can we add a folder ```bangazon/api/fixtures``` (inside our app)

**Review by willsims14 — APPROVED** [review]
Looks good to me

**Review by BlaiseRoberts — APPROVED** [review]

**Pull request merged**
