### PR TITLE
Am product type resource

### PR DESCRIPTION
**Pull request by ANMyers**
## Associated Ticket
[Create Product Type Resource](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/10)

## Description 
Created Product Type table along with corresponding view, serializer, model.
Included Urls.py for testing purposes

*Remember to*:
delete the db.sqlite3 file
 ```python manage.py makemigrations api```
 ```python manage.py migrate```

## Migrations
- [x] Yes
- [ ] No

<p style="text-align: center;"><center>🥔</center></p>

### CODE REVIEW

**Review by willsims14 — APPROVED** [review]
Looks good

**Comment by zakspence** [comment]
looks good! :+1:

**Review by zakspence — APPROVED** [review]
Everything works for me

**Review by BlaiseRoberts — APPROVED** [review]
Looks good to me! 💯

**Pull request merged**
